import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  contentContainer: {
    paddingBottom: 40,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    backgroundColor: "#F8FAFC",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#64748B",
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 24,
    backgroundColor: "#FFFFFF",
  },
  welcomeText: {
    fontSize: 16,
    color: "#64748B",
    marginBottom: 4,
  },
  nameText: {
    fontSize: 28,
    fontWeight: "bold" as const,
    color: "#1E293B",
  },
  errorContainer: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    backgroundColor: "#FEF2F2",
    margin: 20,
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: "#EF4444",
  },
  errorText: {
    color: "#DC2626",
    marginLeft: 8,
    flex: 1,
  },
  completenessCard: {
    backgroundColor: "#FFFFFF",
    margin: 20,
    padding: 20,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  completenessHeader: {
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
    marginBottom: 12,
  },
  completenessTitle: {
    fontSize: 18,
    fontWeight: "600" as const,
    color: "#1E293B",
  },
  completenessPercentage: {
    fontSize: 24,
    fontWeight: "bold" as const,
    color: "#8B5CF6",
  },
  progressBar: {
    height: 8,
    backgroundColor: "#E5E7EB",
    borderRadius: 4,
    marginBottom: 12,
    overflow: "hidden" as const,
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#8B5CF6",
    borderRadius: 4,
  },
  completenessDescription: {
    fontSize: 14,
    color: "#64748B",
    textAlign: "center" as const,
  },
  profileCard: {
    backgroundColor: "#FFFFFF",
    marginHorizontal: 20,
    marginBottom: 16,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "600" as const,
    color: "#1E293B",
    marginLeft: 8,
  },
  emptyCardTitle: {
    color: "#9CA3AF",
  },
  cardContent: {
    padding: 16,
  },
  infoRow: {
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
    marginBottom: 8,
  },
  infoLabel: {
    fontSize: 14,
    fontWeight: "500" as const,
    color: "#64748B",
    flex: 1,
  },
  infoValue: {
    fontSize: 14,
    color: "#1E293B",
    flex: 2,
    textAlign: "right" as const,
  },
  emptyText: {
    fontSize: 14,
    color: "#9CA3AF",
    fontStyle: "italic" as const,
  },
  goalSection: {
    marginBottom: 12,
  },
  goalText: {
    fontSize: 14,
    color: "#374151",
    lineHeight: 20,
    marginTop: 4,
    backgroundColor: "#F8FAFC",
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#8B5CF6",
  },
  detailsText: {
    fontSize: 14,
    color: "#374151",
    lineHeight: 20,
    marginTop: 4,
    backgroundColor: "#F8FAFC",
    padding: 12,
    borderRadius: 8,
  },
  actionSection: {
    paddingHorizontal: 20,
    marginTop: 8,
  },
  primaryButton: {
    backgroundColor: "#8B5CF6",
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    paddingVertical: 16,
    borderRadius: 12,
    shadowColor: "#8B5CF6",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600" as const,
    marginLeft: 8,
  },
  goalsSection: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  goalsSectionTitle: {
    fontSize: 16,
    fontWeight: "600" as const,
    color: "#1E293B",
    marginBottom: 12,
  },
  goalItem: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    marginBottom: 8,
  },
  goalItemText: {
    fontSize: 14,
    color: "#374151",
    marginLeft: 8,
    flex: 1,
  },
  achievedGoal: {
    textDecorationLine: "line-through" as const,
    color: "#9CA3AF",
  },
  moreGoalsText: {
    fontSize: 12,
    color: "#6B7280",
    fontStyle: "italic" as const,
    textAlign: "center" as const,
    marginTop: 8,
  },
  accountSection: {
    paddingHorizontal: 20,
    marginTop: 32,
    gap: 12,
  },
  logoutButton: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    backgroundColor: "#FEF3C7",
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#F59E0B",
  },
  logoutButtonText: {
    color: "#D97706",
    fontSize: 14,
    fontWeight: "500" as const,
    marginLeft: 8,
  },
  deleteButton: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    backgroundColor: "#FEF2F2",
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#EF4444",
  },
  deleteButtonText: {
    color: "#DC2626",
    fontSize: 14,
    fontWeight: "500" as const,
    marginLeft: 8,
  },
  loadingOverlay: {
    alignItems: "center" as const,
    marginTop: 16,
  },
});
